#!/usr/bin/env python3

from pathlib import Path
from urllib import parse as urlparser
import argparse

parser = argparse.ArgumentParser()
command_parsers = parser.add_subparsers(title='Commands', description='Repository configuration commands')
install_parser = command_parsers.add_parser('install', help='Installs infrastructure scripts to enable IPFS directory as remote repository')
install_parser.add_argument('ipfs_id',
                            action='store',
                            nargs=1,
                            help='IPFS CID or IPNS peer name to use as remote ID')
install_parser.add_argument('api_url',
                            action='store',
                            nargs=1,
                            help='IPFS node API URL (API must be active to view the remote Git database!), default is %(default)s',
                            default='http://127.0.0.1')
install_parser.add_argument('api_port',
                            action='store',
                            nargs='?',
                            help='IPFS node API port (will be attached to URL) [%(default)s]',
                            default='5001')
install_parser.add_argument('-t', '--timeout',
                            action='store',
                            required=False,
                            help='Network timeout for API communications',
                            default='30')
config = parser.parse_args()
